version: "3"
# this file same as command line: docker run -v D:\dock\node-docker\:/app -p 3000:3000 -d --name mynodeapp my-node-app-image:mynode
# no volumes in prod, so no bind mount
services:
  nginx:
    ports:
      - "80:80"
  node-app:
    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    command: node index.js
